[package]
name = "neko-tun"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
futures = "0.3.31"
lwip = "0.3.15"
tokio = { version = "1.47.1", features = ["net", "io-util"] }
tun = { version = "0.8.4", features = ["async"] }
