[package]
name = "ssh"
version = "0.1.0"
edition = "2024"
description = "wrapper for russh crate"

[dependencies]
anyhow = "1.0.100"
common = { path = "../../common" }
russh = "0.54.6"
tokio = { version = "1.47.1", features = ["net", "io-util"] }
