[package]
name = "vless"
version = "0.1.0"
edition = "2024"
description = "vless protocol implementation"

[dependencies]
bytes = "1.10.1"
common = { path = "../../common" }
tokio = { version = "1.48.0", features = ["net", "io-util"] }
uuid = "1.18.1"
